spring.application.name=book-service
server.port=8080

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator (for Kubernetes health checks)
management.endpoints.web.exposure.include=health